version: "3.8"
services:
  backend:
    build: ./mp-backend
    ports:
      - "3001:3001"
    env_file:
      - ./mp-backend/.env
    restart: unless-stopped
  frontend:
    build: ./panel-admin
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
